config/routes.rb
Rails.application.routes.draw do

  resources :products
  resources :in_shopping_carts, only: [:create,:destroy]
  devise_for :users
  
  post "/emails/create", as: :create_email
  post "/pagar", to: "payments#create"
  post "/payments/cards", to:"payments#process_card"

  
  get "/carrito", to: "shopping_carts#show"
  get "/add/:product_id",as: :add_to_cart,to: "in_shopping_carts#create" 
  get "/checkout", to: "payments#checkout"
  
  get "/ok", to: "welcome#payment_succed"
  get "/ordenes", to: "ordenes#index"
  
  authenticated :user do
    root 'welcome#index'
  end
  
  unauthenticated :user do
    devise_scope :user do
      root 'welcome#unregistered', as: :unregistered_root
    end
  end
end

app/views/partials/_nav.haml
%header
	%nav.green
		%ul.no-list.no-padding.text-center
			%li.col-md-4.inline-block.tall-padding.white-text
				-if user_signed_in?
					=link_to root_path, class:"right-space white-text" do
						%i.mdi-action-shopping-basket
						Mi tienda
					=link_to carrito_path, class:"right-space white-text" do
						%i.mdi-action-trending-up
						Órdenes
					=link_to "Cerrar sesión",destroy_user_session_path,method: :delete ,class:"right-space white-text"
						
			%li.col-md-4.inline-block.text-center.tall-padding
				=image_tag "tiendus.png",height:"80px"
			%li.col-md-4.inline-block.tall-padding
				=link_to carrito_path,class:"white-text" do
					%i.fa.fa-shopping-cart.fa-3{"aria-hidden" => "true"}
					Mi carrito
					(
					= @shopping_cart.products.count
					)