config/routes.rb
Rails.application.routes.draw do

  resources :products
  resources :in_shopping_carts, only: [:create,:destroy]
  devise_for :users
  
  post "/emails/create", as: :create_email
  post "/pagar", to: "payments#create"
  post "/payments/cards", to:"payments#process_card"

  
  get "/carrito", to: "shopping_carts#show"
  get "/add/:product_id",as: :add_to_cart,to: "in_shopping_carts#create" 
  get "/checkout", to: "payments#checkout"
  
  get "/ok", to: "welcome#payment_succed"
  get "/ordenes", to: "ordenes#index"
  
  authenticated :user do
    root 'welcome#index'
  end
  
  unauthenticated :user do
    devise_scope :user do
      root 'welcome#unregistered', as: :unregistered_root
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @orders = current_user.orders.order("created_at desc")
  end

  def unregistered
  	render layout: "landing"
  end

  def payment_succed
  	if @shopping_cart.payed?
  		cookies[:shopping_cart_id] = nil
  	else
  		redirect_to carrito_path
  	end
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.haml
.col-xs-12.col-md-11.center-block.no-float
	.card.large-padding
		.top-space
			.col-md-3.col-xs-12.inline-block.no-padding.in-top
				.text-center
					=link_to "Crear producto",new_product_path, class:"btn btn-info"
				=render current_user.products
			.col-md-9.col-xs-12.inline-block
				=render "payments/index"

app/views/welcome/payment_succed.haml
.col-md-10.center-block.no-float
	%article.card.large-padding
		%h1 GRACIAS POR TU COMPRA!
		%p Tu pedido llegará a tu Box en 10 minutos. 
		%section.big-top-space
			%h2 Resumen de tu pedido
			%table.table.table-striped.table-hover.medium#table_shopping_cart
				%thead
					%td Producto
					%td Costo
				%tbody
					-@shopping_cart.in_shopping_carts.each do |i_sh|
						-product = i_sh.product
						%tr{id: "#{product.id}"}
							%td= product.name
							%td= product.pricing

app/views/welcome/unregistered.haml
%header.green.big-padding
	.col-md-10.no-float.center-block
		.col-md-6.no-padding.inline-block
			%h1.white-text.ultra-big.kostic 
				%strong
					¡Todos sean Bienvenidos!
			=image_tag "tiendus.png",width:"500"
		.col-md-5.inline-block
			=image_tag "gorilaz1.png",width:"500"
.grey.white-text.big-padding.kostic
	.col-md-10.no-float.center-block
		.absolute{style:"bottom:-4.5em;width:100%;left:0px;"}
			.text-center.big
				.col-md-3.inline-block
					.white.grey-text.circle
						%strong 1
				.col-md-3.inline-block
					.white.grey-text.circle
						%strong 2
				.col-md-3.inline-block
					.white.grey-text.circle
						%strong 3
		%h2.bigger.kostic.text-center
			%strong Todas las canciones que marcaron tu vida.
		%div.text-center.top-space
			.col-md-3.inline-block.text-left
				=image_tag "chicas.png", class:"col-md-10 inline-block"
				.top-space.kostic
					%strong.medium
						Karaoke
					%p.white-text.text-justify.medium.kostic
						Divierte con la comodidad de nuestros boxes privados equipados con pantallas de ultima generación, audio profesional que serán del agrado de tu grupo.
			.col-md-3.inline-block.text-left
				=image_tag "tragos.png", class:"col-md-10 inline-block"
				.top-space.kostic
					%strong.medium
						Bar
					%p.white-text.text-justify.medium
						Disfruta de la variedad de cocteles y piqueos que brindamos para nuestros clientes en nuestra Carta Bar 
			.col-md-3.inline-block.text-left
				=image_tag "box.png", class:"col-md-10 inline-block"
				.top-space.kostic
					%strong.medium
						Boxes
					%p.white-text.text-justify.medium
						Salón Karaoke. con mas de 10,000 temas, reproducidos en pantallas de ultima generación con calidad HDMI y con sistema de Audio profesional
						
						
.red.white-text.big-padding.kostic{style:"margin-top:5em;"}
	.col-md-8.no-float.text-center.center-block
		=image_tag "notas.png",width:"500"
		%p.medium.col-md-11.center-block.no-float.top-space
			%p.big.kostic1 Únete a la mejor cadena de Karaoke a nivel nacional.
			%p.medium Comuníquese con nosotros Central: 613-5000 o visita nuestra <a class="kostic1" href="https://www.facebook.com/KaraokeBar-193363567756680/?fref=ts">FanPage</a> y envianos un mensaje. 
			%p
			=link_to "Nuestros Productos", products_path, class:"btn btn-info kostic1 medium"
			%a.btn.btn-info.kostic1.medium{"aria-pressed" => "true", :href => "https://smartfinal-mcastroascencio.c9users.io", :role => "button"}> Información
			%a.btn.btn-info.kostic1.medium{"aria-pressed" => "true", :href => "https://proyecto-final-jhonataloayza.c9users.io", :role => "button"}> home
.top-space.big-padding
	.col-md-11.col-xs-12.center-block.no-float.kostic1
		=form_tag(create_email_path,method: :post,remote:true,id: "emails-form") do
			=email_field_tag "email",nil,class:"col-xs-12 inline-block text-center landing-form",placeholder:"Escribe aquí tu email"
		#email-info.white-text.red.large-padding.medium